### ISSUE TITLE
Jimp unmaintained

### ISSUE THREAD

**Issue by thomassth** [ragrag/merge-base64#3]
Currently https://github.com/oliver-moran/jimp has not updated in over 2 years, and incompatible with webpack 5.

Author has confirmed need for new maintainers.

https://github.com/oliver-moran/jimp/issues/1079#issuecomment-1102935492

**Comment by ragrag** [comment]
thank you @thomassth, yeah i might consider re-writing this pkg with sharp or some other alternative. don't really have the capacity for it at the moment though

**Comment by ragrag** [comment]
jimp is now updated to latest
