### ISSUE TITLE
Angular components importing v1.1.2 fail to import mergeImages

### ISSUE THREAD

**Issue by Ivaylo2017** [ragrag/merge-base64#5]
Since last release I notice that my modules fail to resolve the import of mergeImages from merge-base64 module.
VSC throws runtime error message :
This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.
Resolving it in the manner described in this StackOverflow works:
(https://stackoverflow.com/questions/68785926/this-module-can-only-be-referenced-with-ecmascript-imports-exports-by-turning-on)
Opening PR with proposed solution

**Comment by ragrag** [comment]
thanks again for the report!

will create new release shortly from merged PR
