### ISSUE TITLE
TypeError: Jimp.read is not a function

### ISSUE THREAD

**Issue by varnguyen** [ragrag/merge-base64#7]
I'm using Next.js (14.2.3) + Typescript and when I encountered this error
![image](https://github.com/ragrag/merge-base64/assets/33864311/1b1d8fa9-01c8-4422-92cb-a70efe8c37df)

**Comment by frascavone** [comment]
> I'm using Next.js (14.2.3) + Typescript and when I encountered this error ![image](https://private-user-images.githubusercontent.com/33864311/333281787-1b1d8fa9-01c8-4422-92cb-a70efe8c37df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NTcxOTksIm5iZiI6MTcxNzc1Njg5OSwicGF0aCI6Ii8zMzg2NDMxMS8zMzMyODE3ODctMWIxZDhmYTktMDFjOC00NDIyLTkyY2ItYTcwZWZlOGMzN2RmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDEwNDEzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4YTE0ZWQ1ZTQ3MDY1YTIxNDU5NzgxYWYwNjE5MTUwOTc5ODZmNGUxZmE4OWMzZTc0MjI2YzFhZGM0YjJlY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dC0kVbsawWEEq8ik1Ja8__9OSEXrclArp0IUguzD80c)

Hi i'm facing the same issue, did you manage to find a solution?

**Comment by varnguyen** [comment]
Hi @frascavone ,

I wrote a function myself without using a library.
Hope it can help you.

```
const mergeBase64 = (imagesBase64: string[]): Promise<string> => {
  return new Promise((resolve) => {
    const images = imagesBase64.map((base64) => {
      const img = new Image()
      img.src = `data:image/jpeg;base64,${base64}`
      return img
    })

    Promise.all(
      images.map(
        (img) =>
          new Promise<void>((res) => {
            img.onload = () => res()
          })
      )
    ).then(() => {
      const totalWidth = Math.max(...images.map((img) => img.width))
      const totalHeight = images.reduce((sum, img) => sum + img.height, 0)

      const canvas = document.createElement('canvas')
      const ctx = canvas.getContext('2d')
      if (!ctx) return

      canvas.width = totalWidth
      canvas.height = totalHeight

      ctx.fillStyle = '#ffffff'
      ctx.fillRect(0, 0, canvas.width, canvas.height)

      let yOffset = 0
      images.forEach((img, index) => {
        const xOffset = (totalWidth - img.width) / 2
        ctx.drawImage(img, xOffset, yOffset)
        yOffset += img.height

        if (index < images.length - 1) {
          ctx.fillStyle = '#c4c4c4'
          ctx.fillRect(0, yOffset, totalWidth, 1)
          yOffset += 1
        }
      })

      resolve(canvas.toDataURL('image/jpeg').split(',')[1])
    })
  })
}
```

**Comment by frascavone** [comment]
> Hi @frascavone ,
> 
> I wrote a function myself without using a library. Hope it can help you.
> 
> ```
> const mergeBase64 = (imagesBase64: string[]): Promise<string> => {
>   return new Promise((resolve) => {
>     const images = imagesBase64.map((base64) => {
>       const img = new Image()
>       img.src = `data:image/jpeg;base64,${base64}`
>       return img
>     })
> 
>     Promise.all(
>       images.map(
>         (img) =>
>           new Promise<void>((res) => {
>             img.onload = () => res()
>           })
>       )
>     ).then(() => {
>       const totalWidth = Math.max(...images.map((img) => img.width))
>       const totalHeight = images.reduce((sum, img) => sum + img.height, 0)
> 
>       const canvas = document.createElement('canvas')
>       const ctx = canvas.getContext('2d')
>       if (!ctx) return
> 
>       canvas.width = totalWidth
>       canvas.height = totalHeight
> 
>       ctx.fillStyle = '#ffffff'
>       ctx.fillRect(0, 0, canvas.width, canvas.height)
> 
>       let yOffset = 0
>       images.forEach((img, index) => {
>         const xOffset = (totalWidth - img.width) / 2
>         ctx.drawImage(img, xOffset, yOffset)
>         yOffset += img.height
> 
>         if (index < images.length - 1) {
>           ctx.fillStyle = '#c4c4c4'
>           ctx.fillRect(0, yOffset, totalWidth, 1)
>           yOffset += 1
>         }
>       })
> 
>       resolve(canvas.toDataURL('image/jpeg').split(',')[1])
>     })
>   })
> }
> ```

Thank you for your answer, the function works fine, unfortunately i need the options to tweak the result images direction. Great work though :+1:

**Comment by ragrag** [comment]
@frascavone @varnguyen  were you using it on the server or on the client?
this package only works on the server

**Comment by frascavone** [comment]
> @frascavone @varnguyen were you using it on the server or on the client? this package only works on the server

I've used it on the client. Thank you for the info

**Comment by ragrag** [comment]
no worries!
